apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-helmgo
  labels:
    app: keycloak-helmgo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-helmgo
  template:
    metadata:
      labels:
        name: keycloak-helmgo
    spec:
      containers:
        - name: keycloak-helmgo
          image: mo053/helmgo:0.0.9-local
          env:
            - name: IN_CLUSTER
              value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8080
      serviceAccount: keycloak-cluster-sa
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-helmgo-svc
spec:
  type: ClusterIP
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 80
     targetPort: 8080
  selector:
    name: "keycloak-helmgo"
  type: "ClusterIP"
